name: 'Hello World Docker Action'
description: 'Greet someone using Docker'
branding:
  icon: 'anchor'
  color: 'blue'

inputs:
  my-name:
    description: 'The name to greet'
    required: true
    default: 'World'

outputs:
  time:
    description: 'The time of the greeting'

runs:
  using: 'docker'
  image: 'Dockerfile'
